### ISSUE TITLE
[KKS] LightingTweaks causes 100% GPU in Character Maker

### ISSUE THREAD

**Issue by fireattack** [IllusionMods/KK_Plugins#110]
After entering Character Maker mode, my GPU usage becomes 100% and stays there.
Removing `KKS_LightingTweaks.dll` immediately fixed this issue.

I believe this probably is the same performance issue mentioned in 91886f29a7684ce1d1bf06a32c9a55b77e1ffeb5, but it seems the patch only fixed for studio, not main game - character maker mode. I downloaded the newest DLL, the issue remains.

**Comment by DeathWeasel1337** [comment]
The performance issue in Studio was due to applying the shadow modifications to all the lights in a scene, which could be a large number depending on the map. In the character maker there should only ever be one light, so I'm not sure what the issue could be. Some people have reported very bad performance in character maker, but I don't know what could cause this, especially since it affects only a small number of people. Could be driver or video card related issues. Not sure how to debug this.

**Comment by ManlyMarco** [comment]
Closing stale issue, if anyone can reproduce the issue on latest release please reopen.
