### ISSUE TITLE
[AI] [UncensorSelector] Both Pixel Penis and Uncensored Penis visible on Silouett Male

### ISSUE THREAD

**Issue by PAdresse** [IllusionMods/KK_Plugins#128]
When switching to silouett/monochrome male the default pixel penis gets rendered at the same time as the selected uncensor with both clipping into each other.

Is there a workaround?

**Comment by PAdresse** [comment]
Ok I think I found out what is happening:
The sillouett male has a own pixelated penis.
Uncensor selector only removes/replaces the penis of the normale male body. This penis however stays visible when switching to the silouett male (maybe a bug in the censored version too aka 2 pixel penises get rendered in the same spot?).

My quickfix/workaround is to hardmod abdata/chara/oo_base.unity3d with SB3Utility and remove the "enabled" checkmark from "p_cm_body_silhouette -> mesh -> cm_o_dan_f" and "p_cm_body_silhouette -> mesh -> cm_o_dan00".

If someone can link me a tutorial how to properly create a zipmod out of this, I would really aprechiate it. A quick duckduck search didn't give a useable result.

**Comment by ManlyMarco** [comment]
How to reproduce this issue? Can you give exact steps on what to open and do?

**Comment by Avvilimento** [comment]
Looks to be pretty much as described (was just coming to mention this).

During an H scene, if Player Base Colour is turned On (making the player a user-defined colour instead of the full-rendered model) it appears that two penises are rendered - the one chosen via the UncensorSelector mod, and an pixelated one. It is effectively invisible in a large number of positions as it occupies the same space and the uncensored one seems to get priority.

Change to a penetrative position, however, and the two no longer exactly share animations and the wayward censored penis becomes visible - albeit partially obscured. Add BetterPenetration on top and the animations deviate further.

NB I was testing using the "[BP4] Cur 1" uncensor. It's possible that others show it to a greater or lesser extent.

**Comment by Avvilimento** [comment]
Verify of course, but this isn't quite 100% resolved in my testing. If you load a save with the transparent player character already enabled the censored penis is still present, but if you toggle the opacity (eg Press 8 twice) it will correct.
