### ISSUE TITLE
[HS2] [Uncensor Selector] No dropdown menu for the male body.

### ISSUE THREAD

**Issue by FutaBoy** [IllusionMods/KK_Plugins#158]
There is no dropdown menu in the male maker, that you can change the male body.
I created some male body mods.

**Comment by ManlyMarco** [comment]
I made a build with it restored but I don't have any way of testing it since I don't have any male body mods. Here's a test build if you'd like to give it a try https://cdn.discordapp.com/attachments/446787129952043009/1041057135250919505/HS2_UncensorSelector.dll
You can let me know how it goes on discord.
