### ISSUE TITLE
Load Outfit resets ShadowColor in ME for hair(not accs).

### ISSUE THREAD

**Issue by drcharlie92** [IllusionMods/KK_Plugins#95]
Steps to reproduce the bug:
1. Loan any chara in Chara maker.
2. Change Shadow color for Back Hair to anything else.
3. Load any new outfits without accs, without abmx.

The the moment you load new outfit, shadow color for hair resets to default.
Idk if it changes any other hair values tho, might be the case.

**Comment by DeathWeasel1337** [comment]
I can't seem to replicate this issue. I tried on KK and KK Sunshine, shadow color on hair stays after loading coordinate cards. There may be some sort of plugin compatibility issue on your end, if you could upload your bepinex folder (minus translations since those are huge and irrelevant) I could try to troubleshoot.
